### ISSUE TITLE
Sieger to use / is wrk the right tool ?

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#245]
Hi,

I've found a tool on **gtihub** , mostly because of https://github.com/GetRayo/rayo.js `README` display bench using it => https://github.com/mcollina/autocannon

This tool seems to be amazing.

Has anyone used it ?

@OvermindDL1 have you tested it ?

Regards,

**Comment by waghanza** [comment]
@mcollina which benefits could has [autocannon](https://github.com/mcollina/autocannon) (comparing to [wrk](https://github.com/wg/wrk))?

**Comment by OvermindDL1** [comment]
Eh, it's written in a JIT'd language, which will both cause variants in the tests and due to not using low level kernel primitives means that it will have overhead in the data conversion on the syscalls.  Initial guess is I don't see how it could be as fast as something like wrk?  Though I'm curious if that's actually what happens, if I get time soon I might whip up a test.

**Comment by mcollina** [comment]
From my tests against Node.js servers, it can produce the same amount of throughput of `wrk`. It definitely requires more CPU and memory, but those are not the bottleneck in the case of Node.js.

It can also use HTTP pipelining, which other tools did not support some years ago.

**Comment by waghanza** [comment]
ok. as `wrk` supports `HTTP pipeline`, I suggest keeping `wrk`

@mcollina thanks for answers

**Comment by OvermindDL1** [comment]
> From my tests against Node.js servers

That's testing node.js client to node.js server, so yes they should be on part, however testing node.js client to something faster like Rust or C++ or so would not be as efficient and would give false results.
