### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by tbrand** [tbrand/which_is_the_fastest#64]
We need CI to check the PR building and working correctly.
The result is not affected to the result of this benchmark since https://github.com/tbrand/which_is_the_fastest/issues/27

**Comment by waghanza** [comment]
@tbrand seems to be contradictory with #27, no ?

**Comment by waghanza** [comment]
@tbrand so, CI **SHOULD** just executes checks / lint

**Comment by waghanza** [comment]
@tbrand Could you enable [travis](https://travis-ci.com/profile/tbrand) so as https://travis-ci.com/tbrand/which_is_the_fastest can work ?

after this all `PR` will trigger a **CI** check

**Comment by waghanza** [comment]
@tbrand sure, but In fact `travis` has done a migration since their was 2 platforms :
+ 1 for private repos
+ 1 for public repos

now it's https://travis-ci.com (it was https://travis-ci.org) + the github integration is much advandce in https://travis-ci.com

the migration annonce was https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

but I can see it is not **already** doable for public repositories

**Comment by tbrand** [comment]
Yeah, the announce says the migration is still work in progress.
So should we wait? or we can migrate to circleci.

**Comment by waghanza** [comment]
I think we can wait. 

@tbrand I will ping you while this migration is complete

**Comment by tbrand** [comment]
Got it.
