### ISSUE TITLE
Different benchmark results

### ISSUE THREAD

**Issue by hiveminded** [tbrand/which_is_the_fastest#73]
Hello can I ask why before some days iris was the fastest but on your last update you change its results, as far as I know Iris is still the same, so what's changed?

At update: 2017-09-04

https://github.com/tbrand/which_is_the_fastest/commit/70ac42b1312602bce695683ee5e886ae08951e59 

| go                        | echo                   |        4.628243 |        4.362947 |        4.466652 |
| go                        | gorilla_mux        |        4.524554 |        4.057697 |        4.336543 |
| go                        | iris                      |        4.573527 |        4.239478 |        4.474351 |

Now ( Last update: 2017-09-05 )

| go                        | echo                  |        4.243314 |        4.035731 |        4.175869 |
| go                        | gorilla_mux        |        4.001856 |        3.807524 |        3.892316 |
| go                        | iris                      |        4.475054 |        4.182971 |        4.271502 |

**1 day back iris was faster than echo, one day after results have been touched**

A note: regex is slower than trie algorithms for routing, so I'm also curious why your benchmarks results shows gorilla mux faster than iris and echo, any go developer knows that gorilla mux is almost 40 times slower than iris, echo and gin...

**Comment by tbrand** [comment]
I've replaced my macbook from 2013 to 2016.

**Comment by tbrand** [comment]
~~I've replaced my macbook from 2031 to 2016~~

Maybe some process consume my pc's resources.
I'll check the consumption before taking benchmark, thanks for the feedback.

**Comment by OvermindDL1** [comment]
It is not just resource consumption but also has to do with it running on a desktop Apple in general as they are turned for foreground applications at the expensive of background applications.  The benchmarks *really* need to be run on a dedicated server (of which I can do at times if you wish, just ping me) as then the results would be far *far* more consistent.

**Comment by OvermindDL1** [comment]
For note, on one of my servers that is decently unused right now I get this (did not run the rest since I got busy), only 2 cores on this one but my big one is in use right now:

| Language (Runtime)        | Framework (Middleware)    |       Max [sec] |       Min [sec] |       Ave [sec] |
|---------------------------|---------------------------|-----------------|-----------------|-----------------|
| crystal                   | kemal                     |        6.358730 |        5.773698 |        6.106440 |
| crystal                   | router_cr                 |        4.740211 |        4.591974 |        4.653183 |
| crystal                   | raze                      |        5.046483 |        4.555724 |        4.914642 |
| go                        | echo                      |        9.858765 |        8.331007 |        8.686410 |
| go                        | gorilla_mux               |        9.409111 |        8.891903 |        9.075090 |
| go                        | iris                      |        9.085841 |        8.808426 |        8.974092 |
| go                        | fasthttprouter            |        5.139427 |        4.846336 |        4.987129 |
| rust                      | iron                      |        6.228257 |        6.106558 |        6.146892 |
| rust                      | nickel                    |        9.571098 |        9.177377 |        9.418915 |
| rust                      | rocket                    |        7.745674 |        7.313642 |        7.457986 |
| elixir                    | plug                      |       17.780236 |       16.046783 |       16.584284 |
| elixir                    | phoenix                   |       18.668509 |       17.995294 |       18.377037 |
| csharp                    | aspnetcore                |        7.717391 |        6.989479 |        7.325782 |

**Comment by pjmtdw** [comment]
@OvermindDL1 Just for curiosity, is your server IPv6 enabled ?
also I want to know whether there's a performance difference between `:3000` and `localhost:3000`
https://github.com/tbrand/which_is_the_fastest/issues/71

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Just for curiosity, is your server IPv6 enabled ?

Behind a corporate firewall, thus no sadly.

> also I want to know whether there's a performance difference between :3000 and localhost:3000
#71

Remind me again soon and I'll try to run a test next time I get time.  But honestly I would not think so.

**Comment by kalicki** [comment]
Close?!
